Taksofon:
  en_zone: str
  ru_zone: str
  ip: 192.168.1.1
  mac: 7C:10:C9:1D:A2:36
  five_themes: False
  lasers: 1
  composers: 0
  body: 0
  depth: 0
  game_en_name: str
  game_ru_name: str
  file_name: str
  scenes:
    Toys: level3Toys
    New Year: NewYear
  led: False

BApp:
  en_zone: str
  ru_zone: str
  ip: 192.168.1.1
  mac: 7C:10:C9:1D:A2:36
  five_themes: True
  game_en_name: str
  game_ru_name: str
  file_name: str
  scenes:
    Tos: level3s
  led: False

BA2pp:
  en_zone: str
